### ISSUE TITLE
The pure css example in the readme.mdown has an @include which should not be there

### ISSUE THREAD

**Issue by mariusGundersen** [mirisuzanne/compass-animation#12]
on line 98, it should read:

``` css
@keyframes my-animation {
  0%, 100% {
    background-color: blue;
  }
  50% {
    background-color: red;
  }
}

body {
  animation: my-animation 10s infinite;
}
```
