### ISSUE TITLE
Is it possible to create a mixin with arguments that are passed to both keyframes and animation?

### ISSUE THREAD

**Issue by prkos** [mirisuzanne/compass-animation#15]
Something like this: 

``` scss
@mixin animate-height($property: max-height, $max-height: 100px, $duration: 1s) {

  @include keyframes($max-height) {
    from {
      max-height: 0;
    }
    to {
      max-height: $max-height; 
    }
  }

  @include animation($max-height $duration ease 0s 1 forwards); 
}
```

Where the name of the keyframes, some property values and animation arguments are passed from mixin arguments? 

Any other way to make it happen? 

I guess the tricky part is that keyframes aren't applied to any selectors, but mixin adds it inside one.

**Comment by mirisuzanne** [comment]
I think Sass 3 might have a `@root` directive that would make your approach possible, but I don't know much about that yet. What about something like this?

``` scss
// start with an empty list
$height-animations: ();

@mixin animate-height($property: max-height, $max-height: 100px, $duration: 1s) {
  // if this height isn't on the list already
  @if not index($height-animations, $max-height) {
    // add it to the list
    $height-animations: append($height-animations, $max-height);
  }

  // animation names can't start with a number
  $name: a#{$max-height};

  // call the animation
  @include animation($name $duration ease 0s 1 forwards); 
}

// at the end of your code, cycle through the list to create your keyframes
@each $max-height in $height-animations {
  // we need the name again
  $name: a#{$max-height};

  @include keyframes($name) {
    from {
      max-height: 0;
    }
    to {
      max-height: $max-height; 
    }
  }
}
```

I just tested that, and it seems to work. The `$name` bit could be more DRY with a function, or by storing name/value pairs in your list?

**Comment by prkos** [comment]
This is excellent! And thank you for a fast reply! 

For me the mixin works as expected, but keyframes aren't generated. Were you able to get keyframes? 

Functions are a bit out of my depth, and mapping in multidimensional lists isn't yet supported it seems. But never mind this concept helps a lot, if only I can find out what I'm doing wrong with keyframes.

**Comment by mirisuzanne** [comment]
Mapping to multi-dimensional lists isn't supported, but you can always break a list down into component lists. But never-mind that, functions are real similar to mixins, and well worth the time to learn:

``` scss
@function height-to-name($height) {
  @return a#{$height};
}

$name: height-to-name(100px); // returns "a100px"
```

Yes, my keyframes are generated, and everything works as expected. Do you have the "animation" gem installed, required in your config, and imported into your sass?

**Comment by prkos** [comment]
Yes I do have the gem, I've used it for animations before and it worked. But I'll test, and learn more about functions, thank you!

**Comment by prkos** [comment]
This works:

``` scss
$name: anim200;

@include keyframes($name) {
  from {
    max-height: 0;
  }
  to {
    max-height: 200px; 
  }
}
```

but the code with @each doesn't

``` scss
@each $max-height in $height-animations {
  // we need the name again
  $name: anim#{$max-height};

  @include keyframes($name) {
    from {
      max-height: 0;
    }
    to {
      max-height: $max-height; 
    }
  }
}
```

This mean it's not a requirement issue right? 

Could you please point me to a guide on how to debug sass? I was able to find out the list does contain 2 values when tested within mixin, which is correct because I applied the mixin twice (different max-heights). But how can I test it inside @each? Is there a way to print variables?

**Comment by mirisuzanne** [comment]
That's right. Not a requirement issue.

Best way to debug is with the `@debug` directive:

``` scss
@each $this in $that {
  @debug $this;
}
```

If you are using the command line, the results will show up in your console. If you are using a third-party GUI app, I'm not sure what will happen. :)

**Comment by prkos** [comment]
Thank you for the tips, it helped a lot. 

In the end the problem was that keyframes @each wasn't located after the selector where the animation mixin was applied. Duh! lol

But I like to keep my mixins in a partials file, and I'm now trying to figure out if there's a way to create keyframes automatically, but keep the @each code in a partials file or some separate file that is always last. 

Currently I have the @each put into a mixin that I call after each declaration where I call the animation mixin. So I have to remember to do that every time I want to use this, I may want to use in other files too. Do you have any idea how this might be done? Or it seems it's impossible, at least with this method?

**Comment by mirisuzanne** [comment]
You should only need to call the mixin once, at the very end of all your styles:

``` scss
// in your mixins partial:
$height-animations: ();

@mixin animate-height($property: max-height, $max-height: 100px, $duration: 1s) {
  @if not index($height-animations, $max-height) {
    $height-animations: append($height-animations, $max-height);
  }
  $name: a#{$max-height};
  @include animation($name $duration ease 0s 1 forwards); 
}

@mixin height-animations($height-animations) {
  @each $max-height in $height-animations {
    $name: a#{$max-height};
    @include keyframes($name) {
      from { max-height: 0; }
      to { max-height: $max-height; }
    }
  }
}

// all over your stylesheets:
.thing { @include animate-height; }

// once, at the very end of everything:
@include height-animations;
```
